Repository viniferraria/webarber-backend, pull requests merged in 2020-11, with the labels that each got.

#91 Hotfix/codacy semicolon
  __tests__/integration/TesteAgendamento.js
  __tests__/integration/TesteRotaModeradores.js
  __tests__/integration/TesteServico.js
  __tests__/integration/TesteUsuario.js
  src/app/controllers/AgendamentoController.js
  src/app/controllers/BarbeariaController.js
  src/app/controllers/UsuarioController.js
  src/app/middleware/eAdmin.js
  src/app/middleware/eModerador.js
Labels: enhancement

#84 Fixed tests
  __tests__/integration/TesteAgendamento.js
  __tests__/integration/TesteBarbearia.js
  src/app/controllers/AgendamentoController.js
  src/app/controllers/BarbeariaController.js
  src/routes.js
Labels: enhancement, fix

#83 Feature/avaliacao
  __tests__/cases.js
  __tests__/integration/TesteAvaliacao.js
  __tests__/integration/integration.test.js
  src/app/controllers/AgendamentoController.js
  src/app/controllers/AvaliacaoController.js
  src/app/models/Agendamento.js
  src/app/models/Avaliacao.js
  src/app/models/Barbearia.js
  src/database/migrations/20201111010653-create-avaliacao.js
  src/database/migrations/20201116131558-update-barbearia-columin-add-media.js
  src/database/migrations/20201122205705-trigger-atualiza-media-barbearia.js
  src/routes.js
Labels: enhancement

#93 Hotfix/migration
  .github/workflows/main.yml
  Dockerfile
  __tests__/cases.js
  __tests__/integration/TesteBarbearia.js
  src/app/controllers/BarbeariaController.js
  src/app/models/Barbearia.js
  src/app/models/Usuario.js
  src/database/migrations/20201115222331-update-barbearia-dias.js
Labels: documentation

#95 Fixado o filtro
  src/app/controllers/UsuarioController.js
  src/routes.js
Labels: enhancement

#97 Hotfix/fix middleware
  __tests__/integration/TesteAvaliacao.js
  src/app/middleware/eAdmin.js
  src/app/middleware/eModerador.js
  src/app/middleware/permitirTipoUsuario.js
  src/routes.js
Labels: enhancement, fix

#98 Hotfix/filtro acesso
  src/routes.js
Labels: enhancement, fix

#99 Hotfix/filtro acesso
  src/routes.js
Labels: enhancement, fix

#100 Hotfix/patch user
  README.md
  src/app/controllers/UsuarioController.js
  src/app/models/Usuario.js
Labels: enhancement, fix
